export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-white via-indigo-50/40 to-white">

      <section className="max-w-5xl mx-auto px-6 py-20">


        <div className="text-center mb-12">

          <div className="inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-5 py-2 text-sm font-medium text-indigo-700 mb-6">
             Soupxor Guidelines
          </div>


          <h1 className="text-5xl font-bold text-gray-900">

            Terms &{" "}
            <span className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-500 bg-clip-text text-transparent">
              Conditions
            </span>

          </h1>


          <p className="mt-5 text-lg text-gray-600">
            Please read these terms before using  Soupxor services and
            online tools.
          </p>


        </div>





        <div className="space-y-6">


          <section className="rounded-3xl border border-white/60 bg-white/70 backdrop-blur-xl shadow-lg p-8">

            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              Use of Our Tools
            </h2>

            <p className="text-gray-600 leading-7">
               Soupxor provides free online tools for personal and
              professional use. Users are responsible for how they use the
              results generated by these tools.
            </p>

          </section>




          <section className="rounded-3xl border border-white/60 bg-white/70 backdrop-blur-xl shadow-lg p-8">

            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              Acceptable Usage
            </h2>

            <p className="text-gray-600 leading-7">
              Users must not misuse the website, attempt unauthorized access,
              or use  Soupxor in any way that may harm the service or other
              users.
            </p>

          </section>




          <section className="rounded-3xl border border-white/60 bg-white/70 backdrop-blur-xl shadow-lg p-8">

            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              Accuracy of Results
            </h2>

            <p className="text-gray-600 leading-7">
              While we aim to provide accurate tools,  Soupxor does not
              guarantee that every result will be completely error-free.
              Users should verify important information independently.
            </p>

          </section>




          <section className="rounded-3xl border border-white/60 bg-white/70 backdrop-blur-xl shadow-lg p-8">

            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              Changes to These Terms
            </h2>

            <p className="text-gray-600 leading-7">
               Soupxor may update these terms from time to time to improve
              transparency and maintain better services.
            </p>

          </section>




          <section className="rounded-3xl border border-white/60 bg-white/70 backdrop-blur-xl shadow-lg p-8">

            <h2 className="text-2xl font-semibold text-gray-900 mb-3">
              Contact
            </h2>

            <p className="text-gray-600 leading-7">
              For questions regarding these terms, contact:
            </p>

            <p className="mt-3 font-semibold text-indigo-600">
              support@ Soupxor.com
            </p>

          </section>


        </div>


      </section>


    </main>
  );
}